### ISSUE TITLE
Namenseingabe wird nicht geprüft

### ISSUE THREAD

**Issue by MichaelMrt03** [MichaelMrt03/Spion#10]
Wenn ich leere Namensfelder habe und auf 'Senden' gehe wird das nächste Formular geladen, obwohl ich nichts eingetragen habe. Dort wäre es besser wenn ein roter Text unten erscheint der sagt "Bitte alle Felder ausfüllen".

Erst wenn alle Felder ausgefüllt sind, sollte abgeschickt werden

**Comment by Sacul65** [comment]
Mache ich
